#!/usr/bin/env python3
import subprocess
from sys import argv


def main():
    client = subprocess.check_output(
        f"IAM_INSTANCE={argv[1]} OAUTH_CALLBACK={argv[2]} dodas-IAMClientRec kubeapps-client",
        shell=True,
    )
    lines = [line for line in client.decode("utf-8").split("\n") if line]

    with open(
        "/usr/local/share/dodast/kubeapps/values.yaml"
    ) as cur_config:
        cur_config_string = cur_config.read()

    cur_config_string = cur_config_string.replace(
        "CLIENT_ID", f'"{lines[-2].strip()}"'
    ).replace("CLIENT_SECRET", f'"{lines[-1].strip()}"')

    with open(
        "/usr/local/share/dodast/kubeapps/values.yaml", "w"
    ) as cur_config:
        cur_config.write(cur_config_string)


if __name__ == "__main__":
    main()