#!/usr/bin/env python3
import subprocess
from sys import argv


def main():
    client = subprocess.check_output(
        "dodas-IAMClientRec kubeapps-client",
        shell=True,
        env={
            "IAM_INSTANCE": argv[1],
            "OAUTH_CALLBACK": argv[2],
            "ACCESS_TOKEN": argv[3],
        })
    lines = [line for line in client.decode("utf-8").split("\n") if line]

    with open(
        "/usr/local/share/dodasts/kubeapps/values.yaml"
    ) as cur_config:
        cur_config_string = cur_config.read()

    cur_config_string = cur_config_string.replace(
        "CLIENT_ID", lines[-2].strip()
    ).replace("CLIENT_SECRET", lines[-1].strip())

    with open(
        "/usr/local/share/dodasts/kubeapps/values.yaml", "w"
    ) as cur_config:
        cur_config.write(cur_config_string)

    # TODO: replace oidc-client-id in api server manifests
    with open(
        "/etc/kubernetes/manifests/kube-apiserver.yaml"
    ) as cur_config:
        cur_config_string = cur_config.read()

    cur_config_string = cur_config_string.replace(
        "--oidc-client-id=kubernetes", "--oidc-client-id="+lines[-2].strip()
    )

    with open(
        "/etc/kubernetes/manifests/kube-apiserver.yaml", "w"
    ) as cur_config:
        cur_config.write(cur_config_string)

if __name__ == "__main__":
    main()
